### ISSUE TITLE
Un marketing block dépend d'une publication au lieu d'un model

### ISSUE THREAD

**Issue by ThomSawyer** [briefmnews/marketing-blocks#22]
Si besoin, on peut remonter marketing-block dans briefme-core

**Comment by souen** [comment]
Changement après discussion avec Edmond.

Ce qui était prévu : on enlève les fields "active" et "label" et on n'ajoute un ManyToMany "publications". Ensuite c'est la liaison avec une publication qui fait que le bloc est actif ou non.

Le problème : dans le back-office, la personne en charge des marketing blocks perd la vision rapide des blocs actifs et inactifs par publication (car tous les blocs "inactifs" sont devenus une grande liste en vrac).
Il voudrait pouvoir voir rapidement les blocs disponibles et ceux actifs pour une publication donnée.
En conditionnant l'affichage d'un bloc à sa liaison avec une publication, on perd l'information de sa publication lorsque le bloc est "inactif".

Solution : on remet un champ "active" et chaque marketing bloc n'est lié qu'à *une* publication (via une FK, donc).

> "C'est un peu plus de travail [parce qu'on devra dupliquer] mais on fera moins de conneries".

(Je change le titre du ticket)

**Comment by ThomSawyer** [comment]
ok
